# Set any local field constant and label overrides here.
# Values in this file take precedence over those set in:
# TrlnArgon:lib/trln_argon/solr_field_defaults.yml

# AUTHORS_DIRECTOR_A:
#   solr_field: :authors_director_a
#   label:
#     en: Director

DONOR:
  solr_field: :donor_a
  label:
    en: Bookplate
LC_CALL_NOS_NORMED:
  solr_field: :lc_call_nos_normed_a
  label:
    en: LCC Normed
LOCAL_ID:
  solr_field: :local_id
  label:
    en: System ID
TITLE_MAIN_INDEXED:
  solr_field: :title_main_indexed_t
  label:
      en: Title Main Indexed
SHELFKEY:
  solr_field: shelfkey
  label:
      en: Shelfkey
SHELF_NUMBERS:
  solr_field: shelf_numbers_tp
  label:
    en: Shelf Number


